// GENERATED by scripts/sync-news-schema.sh from Hermes src/newsroom/schema.js.
// Do not edit here: change Hermes, then re-run the sync. Contract: docs/NEWS_ARTICLE_SCHEMA.md
// Poko Newsroom — article record contract (schemaVersion 1).
//
// One JSON article record per canonical story and language. The Poko
// Newsroom writes records; the website builder validates and renders them.
// This module implements the shared rules of docs/newsroom-article-schema.md:
// the enums, the block shapes, the fact-check verdict evidence rules and the
// market module. Validators return plain arrays of error strings so the
// caller can aggregate them per record.

const EMOJI_RE = /\p{Extended_Pictographic}/u;
const SLUG_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
const ISO_OFFSET_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?(?:Z|[+-]\d{2}:\d{2})$/;
const READING_WPM = 230;

export const TEMPLATE_IDS = Object.freeze(['breaking', 'reveal', 'fact_check', 'market_pulse', 'explainer', 'developing', 'comparison', 'data_deep_dive', 'trend', 'analysis']);
export const ARTICLE_TYPES = Object.freeze(['NEWS', 'BREAKING', 'FACT CHECK', 'ANALYSIS', 'EXPLAINER', 'MARKET', 'DATA']);
export const SECTIONS = Object.freeze(['sets', 'cards', 'market', 'competitive', 'collectors', 'fact-check', 'analysis', 'industry']);
export const STATUSES = Object.freeze(['draft', 'review', 'published', 'blocked', 'withdrawn']);
export const GATE_VERDICTS = Object.freeze(['READY', 'REVIEW', 'BLOCKED']);
export const VERDICTS = Object.freeze(['CONFIRMED', 'SUPPORTED', 'UNVERIFIED', 'DISPUTED', 'MISLEADING', 'FALSE']);
export const BLOCK_TYPES = Object.freeze(['paragraph', 'heading', 'key_facts', 'unknowns', 'fact_check', 'source_comparison', 'why_it_matters', 'context', 'analysis', 'market', 'chart', 'gallery', 'timeline', 'comparison', 'faq', 'related_card', 'related_set', 'methodology', 'quote', 'list', 'update_note']);
export const IMAGE_ORIGINS = Object.freeze(['pokoin_generated', 'pokoin_catalog', 'official_press', 'editorial_source', 'branded_fallback']);
export const IMAGE_RIGHTS = Object.freeze(['owned', 'press_kit', 'editorial_permitted', 'unknown']);
export const MEASUREMENTS = Object.freeze(['asking', 'inferred_sold', 'count']);
export const POKO_AUTHOR = Object.freeze({ id: 'poko', name: 'Poko', role: 'Pokoin News Desk', url: '/news/authors/poko' });
// Pokoin game ids → pokoin.com URL slug (mirrors pokoin-web market/src/game.js).
// Pokémon has no prefix: /news. Every other game: /<slug>/news.
export const GAME_SLUGS = Object.freeze({
  pokemon: '', one_piece: 'one-piece', riftbound: 'riftbound', magic: 'magic', yugioh: 'yugioh', lorcana: 'lorcana',
  flesh_and_blood: 'flesh-and-blood', digimon: 'digimon', dragon_ball_super: 'dragon-ball-super', vanguard: 'vanguard',
  star_wars: 'star-wars', union_arena: 'union-arena', gundam: 'gundam', sorcery: 'sorcery', palworld: 'palworld',
  cyberpunk: 'cyberpunk', weiss_schwarz: 'weiss-schwarz', final_fantasy: 'final-fantasy', force_of_will: 'force-of-will',
  world_of_warcraft: 'world-of-warcraft', battle_spirits_saga: 'battle-spirits-saga', star_wars_destiny: 'star-wars-destiny',
  the_spoils: 'the-spoils', my_little_pony: 'my-little-pony', dragon_born: 'dragon-born',
});
export const GAME_IDS = Object.freeze(Object.keys(GAME_SLUGS));

/** '/news' for Pokémon, '/<slug>/news' for every other game. */
export function gameNewsBase(game = 'pokemon') {
  const slug = GAME_SLUGS[game] || '';
  return slug ? `/${slug}/news` : '/news';
}

/** Public path of an article: '<gameNewsBase>/<slug>'. Never changes once published. */
export function articlePath(record) {
  return `${gameNewsBase(record?.game || 'pokemon')}/${record?.slug || ''}`;
}

export const RESERVED_SLUGS = Object.freeze(['latest', 'sets', 'cards', 'market', 'competitive', 'collectors', 'fact-check', 'analysis', 'industry', 'authors', 'about', 'editorial-policy', 'corrections', 'methodology', 'contact', 'rss', 'sitemap', 'assets', 'media', 'page', 'tags', 'desk']);

export function slugify(text) {
  const raw = String(text || '');
  if (!raw.trim()) return '';
  const normalized = raw
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/['\u2019]/g, '')
    .replace(/&/g, ' and ')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  if (normalized.length <= 80) return normalized;
  const cut = normalized.slice(0, 80);
  const boundary = cut.lastIndexOf('-');
  return (boundary > 0 ? cut.slice(0, boundary) : cut).replace(/-+$/g, '');
}

export function uniqueSlug(base, existingSlugs) {
  const taken = new Set([...RESERVED_SLUGS, ...(existingSlugs || [])]);
  if (!taken.has(base)) return base;
  for (let n = 2; ; n += 1) {
    const candidate = `${base}-${n}`;
    if (!taken.has(candidate)) return candidate;
  }
}

export function isIsoWithOffset(value) {
  if (typeof value !== 'string' || !ISO_OFFSET_RE.test(value)) return false;
  return !Number.isNaN(Date.parse(value));
}

export function countWords(text) {
  const words = String(text || '').trim().split(/\s+/).filter(Boolean);
  return words.length;
}

function pushField(target, value) {
  if (typeof value === 'string' && value.trim()) target.push(value);
}

export function articleText(record) {
  const parts = [];
  if (!record || typeof record !== 'object') return '';
  pushField(parts, record.headline);
  pushField(parts, record.dek);
  for (const block of record.blocks || []) {
    if (!block || typeof block !== 'object') continue;
    pushField(parts, block.text);
    pushField(parts, block.claim);
    pushField(parts, block.explanation);
    pushField(parts, block.summary);
    pushField(parts, block.title);
    for (const item of block.items || []) {
      if (!item || typeof item !== 'object') continue;
      pushField(parts, item.text);
      pushField(parts, item.q);
      pushField(parts, item.a);
    }
    for (const row of block.rows || []) {
      if (!row || typeof row !== 'object') continue;
      pushField(parts, row.label);
      pushField(parts, row.claim);
      for (const value of row.values || []) pushField(parts, value);
      for (const says of row.says || []) pushField(parts, says && says.text);
    }
    for (const column of block.columns || []) pushField(parts, typeof column === 'string' ? column : column && column.name);
  }
  for (const image of record.images || []) pushField(parts, image && image.caption);
  return parts.filter(Boolean).join('\n');
}

export function computeReadingStats(record) {
  const wordCount = countWords(articleText(record));
  const readingMinutes = Math.max(1, Math.round(wordCount / READING_WPM));
  return { wordCount, readingMinutes };
}

function isPositiveInt(value) {
  return Number.isInteger(value) && value > 0;
}

export function validateImageRef(image, { asHero = false } = {}) {
  const errors = [];
  if (!image || typeof image !== 'object') {
    return ['image is required'];
  }
  if (typeof image.id !== 'string' || !image.id.trim()) errors.push('image.id is required');
  if (typeof image.url !== 'string' || !image.url.trim()) errors.push('image.url is required');
  if (typeof image.alt !== 'string' || !image.alt.trim()) errors.push('image.alt is required');
  if (!isPositiveInt(image.width)) errors.push('image.width must be a positive integer');
  if (!isPositiveInt(image.height)) errors.push('image.height must be a positive integer');
  if (!IMAGE_ORIGINS.includes(image.origin)) errors.push('image.origin must be one of ' + IMAGE_ORIGINS.join(', '));
  if (!IMAGE_RIGHTS.includes(image.rights)) errors.push('image.rights must be one of ' + IMAGE_RIGHTS.join(', '));
  if (image.origin !== 'pokoin_generated' && image.origin !== 'branded_fallback') {
    if (typeof image.credit !== 'string' || !image.credit.trim()) errors.push('image.credit is required for this origin');
  }
  if (asHero) {
    if (isPositiveInt(image.width) && image.width < 696) errors.push('hero image must be at least 696 px wide');
    if (image.rights === 'unknown') errors.push('hero image rights must not be unknown');
    if (image.isIllustration === true && image.origin !== 'branded_fallback' && image.origin !== 'pokoin_generated') {
      errors.push('hero image must not be an illustration unless origin is branded_fallback or pokoin_generated');
    }
  }
  return errors;
}

function sourceIdsPresent(ids, record, errors, label) {
  if (ids === undefined || ids === null) return;
  const sourceIds = new Set((record.sources || []).map((source) => source && source.id));
  if (!Array.isArray(ids)) {
    errors.push(`${label} must be an array`);
    return;
  }
  for (const id of ids) {
    if (!sourceIds.has(id)) errors.push(`${label} references unknown source id "${id}"`);
  }
}

function validateVerdictEvidence(block, record, errors) {
  const sourcesById = new Map((record.sources || []).map((source) => [source.id, source]));
  const supportedBy = Array.isArray(block.supportedBy) ? block.supportedBy : [];
  const contradictedBy = Array.isArray(block.contradictedBy) ? block.contradictedBy : [];
  const tierOf = (id) => (sourcesById.get(id) || {}).tier;
  const hasTier = (ids, tiers) => ids.some((id) => tiers.includes(tierOf(id)));

  switch (block.verdict) {
    case 'CONFIRMED':
      if (!hasTier(supportedBy, ['A'])) {
        errors.push('fact_check verdict CONFIRMED requires a tier-A source in supportedBy');
      }
      break;
    case 'SUPPORTED': {
      const tierB = supportedBy.some((id) => tierOf(id) === 'B');
      const tierCIds = new Set(supportedBy.filter((id) => tierOf(id) === 'C' && id));
      if (!tierB && tierCIds.size < 2) {
        errors.push('fact_check verdict SUPPORTED requires a tier-B source, or at least 2 tier-C sources, in supportedBy');
      }
      if (hasTier(contradictedBy, ['A', 'B'])) {
        errors.push('fact_check verdict SUPPORTED is invalid while a tier-A or tier-B source contradicts the claim');
      }
      break;
    }
    case 'DISPUTED':
      if (!supportedBy.length || !contradictedBy.length) {
        errors.push('fact_check verdict DISPUTED requires both supportedBy and contradictedBy to be non-empty');
      }
      break;
    case 'MISLEADING':
    case 'FALSE':
      if (!hasTier(contradictedBy, ['A', 'B'])) {
        errors.push(`fact_check verdict ${block.verdict} requires a tier-A or tier-B source in contradictedBy`);
      }
      break;
    case 'UNVERIFIED':
      break;
    default:
      break;
  }
}

export function validateBlock(block, record) {
  const errors = [];
  if (!block || typeof block !== 'object') return ['block must be an object'];
  const type = block.type;
  if (!BLOCK_TYPES.includes(type)) {
    return [`unknown block type "${type}"`];
  }
  if (type === 'paragraph') {
    if (typeof block.text !== 'string' || !block.text.trim()) errors.push('paragraph.text is required');
    sourceIdsPresent(block.sourceIds, record, errors, 'paragraph.sourceIds');
  } else if (type === 'heading') {
    if (typeof block.text !== 'string' || !block.text.trim()) errors.push('heading.text is required');
  } else if (type === 'key_facts') {
    if (!Array.isArray(block.items) || block.items.length < 1) errors.push('key_facts.items must be a non-empty array');
    for (const [index, item] of (block.items || []).entries()) {
      if (!item || typeof item.text !== 'string' || !item.text.trim()) errors.push(`key_facts.items[${index}].text is required`);
      sourceIdsPresent(item.sourceIds, record, errors, `key_facts.items[${index}].sourceIds`);
    }
  } else if (type === 'unknowns') {
    if (!Array.isArray(block.items) || block.items.length < 1) errors.push('unknowns.items must be a non-empty array');
    for (const [index, item] of (block.items || []).entries()) {
      if (!item || typeof item.text !== 'string' || !item.text.trim()) errors.push(`unknowns.items[${index}].text is required`);
    }
  } else if (type === 'fact_check') {
    if (typeof block.claim !== 'string' || !block.claim.trim()) errors.push('fact_check.claim is required');
    if (!VERDICTS.includes(block.verdict)) errors.push(`fact_check.verdict must be one of ${VERDICTS.join(', ')}`);
    if (typeof block.explanation !== 'string' || !block.explanation.trim()) errors.push('fact_check.explanation is required');
    sourceIdsPresent(block.supportedBy, record, errors, 'fact_check.supportedBy');
    sourceIdsPresent(block.contradictedBy, record, errors, 'fact_check.contradictedBy');
    if (block.primarySourceId !== undefined && block.primarySourceId !== null) {
      const sourceIds = new Set((record.sources || []).map((source) => source && source.id));
      if (!sourceIds.has(block.primarySourceId)) errors.push(`fact_check.primarySourceId references unknown source id "${block.primarySourceId}"`);
    }
    if (VERDICTS.includes(block.verdict)) validateVerdictEvidence(block, record, errors);
  } else if (type === 'source_comparison') {
    if (!Array.isArray(block.rows) || block.rows.length < 1) errors.push('source_comparison.rows must be a non-empty array');
    for (const [index, row] of (block.rows || []).entries()) {
      if (!row || typeof row.claim !== 'string' || !row.claim.trim()) errors.push(`source_comparison.rows[${index}].claim is required`);
      if (!Array.isArray(row.says) || row.says.length < 1) errors.push(`source_comparison.rows[${index}].says must be a non-empty array`);
      for (const [sayIndex, says] of (row.says || []).entries()) {
        const sourceIds = new Set((record.sources || []).map((source) => source && source.id));
        if (!sourceIds.has(says.sourceId)) errors.push(`source_comparison.rows[${index}].says[${sayIndex}].sourceId references unknown source id "${says.sourceId}"`);
        if (typeof says.text !== 'string' || !says.text.trim()) errors.push(`source_comparison.rows[${index}].says[${sayIndex}].text is required`);
      }
    }
  } else if (type === 'why_it_matters' || type === 'context' || type === 'analysis' || type === 'methodology') {
    if (typeof block.text !== 'string' || !block.text.trim()) errors.push(`${type}.text is required`);
  } else if (type === 'market') {
    if (!record.market || record.market.sufficient !== true) {
      errors.push('market block requires article.market with sufficient: true');
    }
  } else if (type === 'chart') {
    if (typeof block.chartId !== 'string' || !block.chartId) errors.push('chart.chartId is required');
    const chartIds = new Set(((record.market || {}).charts || []).map((chart) => chart && chart.id));
    if (!chartIds.has(block.chartId)) errors.push(`chart.chartId references unknown chart "${block.chartId}"`);
  } else if (type === 'gallery') {
    if (!Array.isArray(block.imageIds) || block.imageIds.length < 1) errors.push('gallery.imageIds must be a non-empty array');
    const imageIds = new Set((record.images || []).map((image) => image && image.id));
    for (const id of block.imageIds || []) {
      if (!imageIds.has(id)) errors.push(`gallery.imageIds references unknown image "${id}"`);
    }
  } else if (type === 'timeline') {
    if (!Array.isArray(block.items) || block.items.length < 1) errors.push('timeline.items must be a non-empty array');
    for (const [index, item] of (block.items || []).entries()) {
      if (!item || !isIsoWithOffset(item.at)) errors.push(`timeline.items[${index}].at must be an ISO-8601 date with offset`);
      if (!item || typeof item.text !== 'string' || !item.text.trim()) errors.push(`timeline.items[${index}].text is required`);
      sourceIdsPresent(item.sourceIds, record, errors, `timeline.items[${index}].sourceIds`);
    }
  } else if (type === 'comparison') {
    if (!Array.isArray(block.columns) || block.columns.length < 2) errors.push('comparison.columns must be an array with at least 2 entries');
    if (!Array.isArray(block.rows) || block.rows.length < 1) errors.push('comparison.rows must be a non-empty array');
    for (const [index, row] of (block.rows || []).entries()) {
      if (!row || typeof row.label !== 'string' || !row.label.trim()) errors.push(`comparison.rows[${index}].label is required`);
      if (!Array.isArray(row.values) || row.values.length !== block.columns.length) {
        errors.push(`comparison.rows[${index}].values must have one value per column`);
      }
    }
  } else if (type === 'faq') {
    if (!Array.isArray(block.items) || block.items.length < 1) errors.push('faq.items must be a non-empty array');
    for (const [index, item] of (block.items || []).entries()) {
      if (!item || typeof item.q !== 'string' || !item.q.trim()) errors.push(`faq.items[${index}].q is required`);
      if (!item || typeof item.a !== 'string' || !item.a.trim()) errors.push(`faq.items[${index}].a is required`);
    }
  } else if (type === 'related_card') {
    if (typeof block.cardId !== 'string' || !block.cardId) errors.push('related_card.cardId is required');
    const cardIds = new Set(((record.related || {}).cards || []).map((card) => card && card.cardId));
    if (!cardIds.has(block.cardId)) errors.push(`related_card.cardId references unknown card "${block.cardId}"`);
  } else if (type === 'related_set') {
    if (typeof block.slug !== 'string' || !block.slug) errors.push('related_set.slug is required');
    const setSlugs = new Set(((record.related || {}).sets || []).map((set) => set && set.slug));
    if (!setSlugs.has(block.slug)) errors.push(`related_set.slug references unknown set "${block.slug}"`);
  } else if (type === 'quote') {
    if (typeof block.text !== 'string' || !block.text.trim()) errors.push('quote.text is required');
    if (countWords(block.text) > 30) errors.push('quote.text must be at most 30 words');
    const sourceIds = new Set((record.sources || []).map((source) => source && source.id));
    if (!sourceIds.has(block.sourceId)) errors.push(`quote.sourceId references unknown source id "${block.sourceId}"`);
  } else if (type === 'list') {
    if (!Array.isArray(block.items) || block.items.length < 1) errors.push('list.items must be a non-empty array');
    for (const [index, item] of (block.items || []).entries()) {
      if (typeof item !== 'string' || !item.trim()) errors.push(`list.items[${index}] must be a non-empty string`);
    }
  } else if (type === 'update_note') {
    if (!isIsoWithOffset(block.at)) errors.push('update_note.at must be an ISO-8601 date with offset');
    if (typeof block.text !== 'string' || !block.text.trim()) errors.push('update_note.text is required');
  }
  return errors;
}

export function validateMarketModule(market) {
  const errors = [];
  if (market === null) return errors;
  if (!market || typeof market !== 'object') return ['market module must be an object or null'];
  if (!market.subject || typeof market.subject !== 'object') errors.push('market.subject is required');
  else if (typeof market.subject.name !== 'string' || !market.subject.name.trim()) errors.push('market.subject.name is required');
  if (!market.window || typeof market.window !== 'object') errors.push('market.window is required');
  else {
    if (!DATE_RE.test(market.window.from)) errors.push('market.window.from must be a YYYY-MM-DD date');
    if (!DATE_RE.test(market.window.to)) errors.push('market.window.to must be a YYYY-MM-DD date');
  }
  if (market.currency !== 'PKN') errors.push('market.currency must be "PKN"');
  if (!Array.isArray(market.metrics)) errors.push('market.metrics must be an array');
  for (const [index, metric] of (market.metrics || []).entries()) {
    const where = `market.metrics[${index}]`;
    if (!metric || typeof metric !== 'object') { errors.push(`${where} must be an object`); continue; }
    if (typeof metric.id !== 'string' || !metric.id.trim()) errors.push(`${where}.id is required`);
    if (typeof metric.label !== 'string' || !metric.label.trim()) errors.push(`${where}.label is required`);
    if (typeof metric.value !== 'number' || Number.isNaN(metric.value)) errors.push(`${where}.value must be a number`);
    if (typeof metric.unit !== 'string' || !metric.unit.trim()) errors.push(`${where}.unit is required`);
    if (!MEASUREMENTS.includes(metric.measurement)) errors.push(`${where}.measurement must be one of ${MEASUREMENTS.join(', ')}`);
    if (typeof metric.definition !== 'string' || !metric.definition.trim()) errors.push(`${where}.definition is required`);
  }
  if (!Array.isArray(market.charts)) errors.push('market.charts must be an array');
  for (const [index, chart] of (market.charts || []).entries()) {
    const where = `market.charts[${index}]`;
    if (!chart || typeof chart !== 'object') { errors.push(`${where} must be an object`); continue; }
    if (typeof chart.id !== 'string' || !chart.id.trim()) errors.push(`${where}.id is required`);
    if (!['line', 'bar'].includes(chart.kind)) errors.push(`${where}.kind must be "line" or "bar"`);
    if (typeof chart.title !== 'string' || !chart.title.trim()) errors.push(`${where}.title is required`);
    if (!MEASUREMENTS.includes(chart.measurement)) errors.push(`${where}.measurement must be one of ${MEASUREMENTS.join(', ')}`);
    if (typeof chart.unit !== 'string' || !chart.unit.trim()) errors.push(`${where}.unit is required`);
    if (!Array.isArray(chart.series) || chart.series.length < 1) errors.push(`${where}.series must be a non-empty array`);
    for (const [seriesIndex, series] of (chart.series || []).entries()) {
      const seriesWhere = `${where}.series[${seriesIndex}]`;
      if (!series || typeof series !== 'object') { errors.push(`${seriesWhere} must be an object`); continue; }
      if (typeof series.label !== 'string' || !series.label.trim()) errors.push(`${seriesWhere}.label is required`);
      if (!Array.isArray(series.points) || series.points.length < 1) errors.push(`${seriesWhere}.points must be a non-empty array`);
      for (const [pointIndex, point] of (series.points || []).entries()) {
        if (!point || typeof point !== 'object') { errors.push(`${seriesWhere}.points[${pointIndex}] must be an object`); continue; }
        if (typeof point.x !== 'string' || !point.x.trim()) errors.push(`${seriesWhere}.points[${pointIndex}].x is required`);
        if (typeof point.y !== 'number' || Number.isNaN(point.y)) errors.push(`${seriesWhere}.points[${pointIndex}].y must be a number`);
      }
    }
    if (typeof chart.summary !== 'string' || !chart.summary.trim()) errors.push(`${where}.summary is required`);
  }
  if (!Number.isInteger(market.observations)) errors.push('market.observations must be an integer');
  if (typeof market.sufficient !== 'boolean') errors.push('market.sufficient must be a boolean');
  if (typeof market.sourceNote !== 'string' || !market.sourceNote.trim()) errors.push('market.sourceNote is required');
  return errors;
}

function deepEquals(a, b) {
  if (a === b) return true;
  if (typeof a !== 'object' || typeof b !== 'object' || !a || !b) return false;
  const keysA = Object.keys(a);
  const keysB = Object.keys(b);
  if (keysA.length !== keysB.length) return false;
  return keysA.every((key) => deepEquals(a[key], b[key]));
}

export function validateArticle(record) {
  const errors = [];
  const warnings = [];
  if (!record || typeof record !== 'object') return { ok: false, errors: ['article record must be an object'], warnings };

  if (record.schemaVersion !== 1) errors.push('schemaVersion must be 1');
  if (typeof record.id !== 'string' || !record.id) errors.push('id is required');
  if (typeof record.slug !== 'string' || !SLUG_RE.test(record.slug) || record.slug.length < 8 || record.slug.length > 90) {
    errors.push('slug must match ^[a-z0-9]+(?:-[a-z0-9]+)*$ and be 8-90 chars');
  }
  if (typeof record.canonicalStoryId !== 'string' || !record.canonicalStoryId) errors.push('canonicalStoryId is required');
  if (record.language !== 'en') errors.push('language must be "en"');
  if (record.editionOf !== null && typeof record.editionOf !== 'string') errors.push('editionOf must be a string or null');
  if (!STATUSES.includes(record.status)) errors.push(`status must be one of ${STATUSES.join(', ')}`);
  if (!TEMPLATE_IDS.includes(record.template)) errors.push(`template must be one of ${TEMPLATE_IDS.join(', ')}`);
  if (!ARTICLE_TYPES.includes(record.articleType)) errors.push(`articleType must be one of ${ARTICLE_TYPES.join(', ')}`);
  if (!SECTIONS.includes(record.section)) errors.push(`section must be one of ${SECTIONS.join(', ')}`);
  if (!GAME_IDS.includes(record.game)) errors.push(`game must be one of ${GAME_IDS.join(', ')}`);

  if (!record.gate || typeof record.gate !== 'object') {
    errors.push('gate is required');
  } else {
    if (!GATE_VERDICTS.includes(record.gate.verdict)) errors.push(`gate.verdict must be one of ${GATE_VERDICTS.join(', ')}`);
    if (!Array.isArray(record.gate.checks)) errors.push('gate.checks must be an array');
    for (const [index, check] of (record.gate.checks || []).entries()) {
      if (!check || typeof check !== 'object') { errors.push(`gate.checks[${index}] must be an object`); continue; }
      if (typeof check.id !== 'string' || !check.id) errors.push(`gate.checks[${index}].id is required`);
      if (typeof check.pass !== 'boolean') errors.push(`gate.checks[${index}].pass must be a boolean`);
      if (typeof check.detail !== 'string') errors.push(`gate.checks[${index}].detail must be a string`);
    }
    if (!isIsoWithOffset(record.gate.evaluatedAt)) errors.push('gate.evaluatedAt must be an ISO-8601 date with offset');
  }

  if (typeof record.headline !== 'string' || record.headline.length < 20 || record.headline.length > 110) {
    errors.push('headline must be 20-110 chars');
  } else {
    if (EMOJI_RE.test(record.headline)) errors.push('headline must not contain emoji');
    if (record.headline.endsWith('.')) errors.push('headline must not end with a period');
  }
  if (typeof record.dek !== 'string' || record.dek.length < 40 || record.dek.length > 220) {
    errors.push('dek must be 40-220 chars');
  }
  if (!deepEquals(record.author, POKO_AUTHOR)) {
    errors.push('author must be exactly the Poko author object');
  }

  if (record.datePublished === null) {
    if (record.status === 'published' || !['draft', 'review', 'blocked'].includes(record.status)) {
      errors.push('datePublished may only be null while the article is draft, review or blocked');
    }
  } else if (!isIsoWithOffset(record.datePublished)) {
    errors.push('datePublished must be an ISO-8601 date with offset');
  }
  if (record.dateModified === null && record.datePublished === null && ['draft', 'review', 'blocked'].includes(record.status)) {
    // Unpublished records carry no public dates yet.
  } else if (!isIsoWithOffset(record.dateModified)) {
    errors.push('dateModified must be an ISO-8601 date with offset');
  } else if (record.datePublished !== null && isIsoWithOffset(record.datePublished)) {
    if (new Date(record.dateModified).getTime() < new Date(record.datePublished).getTime()) {
      errors.push('dateModified must not be earlier than datePublished');
    }
  }

  if (record.hero === null) {
    warnings.push('hero is null; the branded fallback artwork will be rendered');
  } else {
    for (const error of validateImageRef(record.hero, { asHero: true })) errors.push(`hero: ${error}`);
  }
  if (!Array.isArray(record.images) || record.images.length > 12) {
    errors.push('images must be an array of at most 12 entries');
  } else {
    const seen = new Set();
    record.images.forEach((image, index) => {
      if (!image || typeof image !== 'object') { errors.push(`images[${index}] must be an object`); return; }
      for (const error of validateImageRef(image)) errors.push(`images[${index}]: ${error}`);
      if (image.rights === 'unknown') errors.push(`images[${index}]: rights "unknown" images are never used in a gallery`);
      if (image.id) {
        if (seen.has(image.id)) errors.push(`images[${index}]: duplicate image id "${image.id}"`);
        seen.add(image.id);
      }
    });
  }

  if (!Array.isArray(record.blocks) || record.blocks.length < 1 || record.blocks.length > 60) {
    errors.push('blocks must be an array of 1-60 entries');
  } else {
    record.blocks.forEach((block, index) => {
      for (const error of validateBlock(block, record)) errors.push(`blocks[${index}]: ${error}`);
    });
  }

  if (!Array.isArray(record.sources) || record.sources.length < 1) {
    errors.push('sources must be a non-empty array');
  } else {
    const seen = new Set();
    let secondaryStarted = false;
    record.sources.forEach((source, index) => {
      const where = `sources[${index}]`;
      if (!source || typeof source !== 'object') { errors.push(`${where} must be an object`); return; }
      if (typeof source.id !== 'string' || !source.id) errors.push(`${where}.id is required`);
      else if (seen.has(source.id)) errors.push(`${where}: duplicate source id "${source.id}"`);
      else seen.add(source.id);
      if (typeof source.outlet !== 'string' || !source.outlet) errors.push(`${where}.outlet is required`);
      if (typeof source.url !== 'string' || !/^https?:\/\//.test(source.url)) errors.push(`${where}.url must be an http(s) URL`);
      if (!['A', 'B', 'C', 'D'].includes(source.tier)) errors.push(`${where}.tier must be one of A, B, C, D`);
      if (!['primary', 'secondary'].includes(source.role)) errors.push(`${where}.role must be "primary" or "secondary"`);
      if (source.role === 'secondary') secondaryStarted = true;
      else if (secondaryStarted) errors.push(`${where}: primary sources must be listed before secondary sources`);
    });
  }

  if (record.related !== undefined && record.related !== null) {
    const related = record.related;
    if (typeof related !== 'object') errors.push('related must be an object');
    else {
      if (!Array.isArray(related.cards)) errors.push('related.cards must be an array');
      if (!Array.isArray(related.sets)) errors.push('related.sets must be an array');
    }
  }

  for (const error of validateMarketModule(record.market)) errors.push(error);

  if (!Array.isArray(record.updates)) errors.push('updates must be an array');
  for (const [index, update] of (record.updates || []).entries()) {
    if (!isIsoWithOffset(update.at)) errors.push(`updates[${index}].at must be an ISO-8601 date with offset`);
    if (typeof update.text !== 'string' || !update.text.trim()) errors.push(`updates[${index}].text is required`);
  }
  if (!Array.isArray(record.corrections)) errors.push('corrections must be an array');
  for (const [index, correction] of (record.corrections || []).entries()) {
    if (!isIsoWithOffset(correction.at)) errors.push(`corrections[${index}].at must be an ISO-8601 date with offset`);
    if (typeof correction.previous !== 'string' || !correction.previous.trim()) errors.push(`corrections[${index}].previous is required`);
    if (typeof correction.corrected !== 'string' || !correction.corrected.trim()) errors.push(`corrections[${index}].corrected is required`);
  }

  if (!Array.isArray(record.revisions) || record.revisions.length < 1) {
    errors.push('revisions must be a non-empty array');
  } else {
    let lastMaterial = null;
    for (const [index, revision] of record.revisions.entries()) {
      if (!revision || typeof revision !== 'object') { errors.push(`revisions[${index}] must be an object`); continue; }
      if (!isIsoWithOffset(revision.at)) errors.push(`revisions[${index}].at must be an ISO-8601 date with offset`);
      if (typeof revision.material !== 'boolean') errors.push(`revisions[${index}].material must be a boolean`);
      if (revision.material === true && (lastMaterial === null || new Date(revision.at).getTime() >= new Date(lastMaterial.at).getTime())) {
        lastMaterial = revision;
      }
    }
    if (record.status === 'published' && lastMaterial && isIsoWithOffset(record.dateModified)) {
      if (record.dateModified !== lastMaterial.at) {
        errors.push('dateModified must equal the "at" of the last material revision for a published article');
      }
    }
  }

  if (!Array.isArray(record.tags)) errors.push('tags must be an array');
  else for (const tag of record.tags) if (typeof tag !== 'string' || tag !== tag.toLowerCase()) errors.push('tags must be lowercase strings');

  if (record.scores !== undefined && record.scores !== null && typeof record.scores !== 'object') {
    errors.push('scores must be an object');
  }
  if (record.seo !== undefined && record.seo !== null) {
    if (typeof record.seo !== 'object') errors.push('seo must be an object');
    else {
      if (typeof record.seo.title !== 'string' || !record.seo.title.trim()) errors.push('seo.title is required');
      if (typeof record.seo.description !== 'string' || !record.seo.description.trim()) errors.push('seo.description is required');
    }
  }
  if (record.generation !== undefined && record.generation !== null) {
    if (typeof record.generation !== 'object') errors.push('generation must be an object');
  }

  return { ok: errors.length === 0, errors, warnings };
}
