#!/usr/bin/env bash
# Copy the newsroom article validator from Hermes (the writer) into the website
# renderer. Both sides must validate the same contract: docs/NEWS_ARTICLE_SCHEMA.md.
#   scripts/sync-news-schema.sh [path/to/Hermes]
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HERMES="${1:-/home/nez/Projects/Hermes-newsroom}"
src="$HERMES/src/newsroom/schema.js"
[[ -f "$src" ]] || { echo "missing $src" >&2; exit 1; }
{
  echo "// GENERATED by scripts/sync-news-schema.sh from Hermes src/newsroom/schema.js."
  echo "// Do not edit here: change Hermes, then re-run the sync. Contract: docs/NEWS_ARTICLE_SCHEMA.md"
  cat "$src"
} > "$ROOT/news/lib/schema.mjs"
echo "synced $(wc -l < "$ROOT/news/lib/schema.mjs") lines"
