import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import {
  C1_DICTIONARY,
  C1_FORMAT_VERSION,
  C1_MEDIA_TYPE,
  C1Error,
  decodeC1,
  isC1,
} from './compact.js';

const HANDOFF = fileURLToPath(new URL('../../docs/handoff/compact-c1/', import.meta.url));

function read(path) {
  return JSON.parse(readFileSync(`${HANDOFF}${path}`, 'utf8'));
}

/** Captured production responses, with the `c1` the Rust encoder produced. */
const FIXTURES = [
  'artist-arita',
  'card-versions-card',
  'card-versions-expansion',
  'card-versions-pikachu',
  'expansion-base-set',
  'expansion-destined-rivals',
  'home-page',
  'rails-best-sellers',
  'rails-new-cards',
  'rails-spotlight',
  'search-charizard',
];

// The whole point of the format: the browser must rebuild the exact body the
// route serves as plain JSON, for real payloads encoded by the real encoder.
// Regenerate the `c1/` inputs with
//   cd pokoin-rust && cargo run --release --example c1_measure -- \
//     ../docs/handoff/compact-c1/c1 ../docs/handoff/compact-c1/fixtures/*.json
// (then delete the `*.default.json` it also writes).
for (const name of FIXTURES) {
  test(`decodeC1 rebuilds ${name} exactly`, () => {
    const expected = read(`fixtures/${name}.json`);
    const payload = read(`c1/${name}.c1.json`);
    assert.equal(payload.c1, C1_FORMAT_VERSION);
    assert.equal(payload.dict, C1_DICTIONARY.version);
    const decoded = decodeC1(payload);
    // Stringify, not deepEqual: key order is part of the frozen contract.
    assert.equal(JSON.stringify(decoded), JSON.stringify(expected));
  });
}

test('the bundled dictionary matches the Rust tables', () => {
  // Generated by `cargo run --quiet --example c1_dictionary`; the Rust test
  // `compact::dict::tests::the_committed_snapshot_matches_the_tables` keeps the
  // file in step with `compact::dict`, and this keeps `compact.js` in step with
  // the file.
  const committed = JSON.parse(
    readFileSync(fileURLToPath(new URL('./compact-dictionary.json', import.meta.url)), 'utf8'),
  );
  assert.deepEqual(JSON.parse(JSON.stringify(C1_DICTIONARY)), committed);
});

test('dictionary codes are one-based and never renumbered', () => {
  // Append-only: these codes are load-bearing for every payload already in a
  // CDN cache, so they must not move.
  assert.equal(C1_DICTIONARY.codeBase, 1);
  assert.equal(C1_DICTIONARY.tables.games[0], 'pokemon');
  assert.equal(C1_DICTIONARY.tables.languages[0], 'EN');
  assert.equal(C1_DICTIONARY.tables.conditions[1], 'NM');
  assert.equal(C1_DICTIONARY.tables.nationalities[0], 'western');
  assert.equal(C1_DICTIONARY.tables.artLayouts[0], 'window');
  assert.equal(C1_DICTIONARY.urlPrefixes[0], 'https://cdn.pokoin.com/');
  assert.equal(C1_DICTIONARY.flags.firstEdition, 1);
  assert.equal(C1_DICTIONARY.flags.signed, 2);
});

test('isC1 only recognises a c1 document', () => {
  assert.equal(isC1({ c1: 1, b: {}, t: [] }), true);
  assert.equal(isC1({ cards: [] }), false);
  assert.equal(isC1({ c1: 2 }), false);
  assert.equal(isC1([]), false);
  assert.equal(isC1(null), false);
  assert.equal(isC1(undefined), false);
  assert.equal(isC1('c1'), false);
  assert.equal(C1_MEDIA_TYPE, 'application/vnd.pokoin.c1+json');
});

test('a table rebuilds rows in column order', () => {
  const decoded = decodeC1({
    c1: 1,
    dict: '1',
    b: { cards: { $c1: 0 } },
    t: [
      {
        n: 3,
        k: ['id', 'card_id', 'set', 'nationality', 'imageUrl'],
        c: [
          { c: 3, z: 100, d: [1, 1], ns: 1 },
          { c: 4, r: 0, ns: 1 },
          { c: 0, v: 'Base Set' },
          { c: 2, t: 'nationalities', p: [1, 2], x: [0, 1, 0] },
          { c: 1, v: ['a', 'b', 'c'], prei: 6, suf: '.jpg' },
        ],
      },
    ],
  });
  assert.equal(
    JSON.stringify(decoded),
    JSON.stringify({
      cards: [
        { id: '100', card_id: '100', set: 'Base Set', nationality: 'western', imageUrl: '/card-images/a.jpg' },
        { id: '101', card_id: '101', set: 'Base Set', nationality: 'japanese', imageUrl: '/card-images/b.jpg' },
        { id: '102', card_id: '102', set: 'Base Set', nationality: 'western', imageUrl: '/card-images/c.jpg' },
      ],
    }),
  );
});

test('a palette entry the dictionary does not carry stays a literal', () => {
  const decoded = decodeC1({
    c1: 1,
    dict: '1',
    b: { $c1: 0 },
    t: [{ n: 3, k: ['rarity'], c: [{ c: 2, t: 'rarities', p: [2, 'WCD 2006'], x: [0, 1, 1] }] }],
  });
  assert.deepEqual(decoded, [{ rarity: 'Common' }, { rarity: 'WCD 2006' }, { rarity: 'WCD 2006' }]);
});

test('a presence mask leaves absent keys off the row', () => {
  const decoded = decodeC1({
    c1: 1,
    dict: '1',
    b: { $c1: 0 },
    t: [{ n: 3, k: ['a'], c: [{ c: 1, v: ['x', 'z'], m: [1, 0, 1] }] }],
  });
  assert.equal(JSON.stringify(decoded), JSON.stringify([{ a: 'x' }, {}, { a: 'z' }]));
});

test('a vector table rebuilds a flat array', () => {
  const decoded = decodeC1({
    c1: 1,
    dict: '1',
    b: { sections: { bestSellerIds: { $c1: 0 } } },
    t: [{ n: 3, c: [{ c: 3, z: 612454, d: [10, 5], ns: 1 }] }],
  });
  assert.deepEqual(decoded, { sections: { bestSellerIds: ['612454', '612464', '612469'] } });
});

test('a body that itself uses the marker key survives', () => {
  const decoded = decodeC1({
    c1: 1,
    dict: '1',
    b: { $c1x: { $c1: 3, other: 1 } },
    t: [],
  });
  assert.deepEqual(decoded, { $c1: 3, other: 1 });
});

test('a malformed document throws C1Error rather than returning junk', () => {
  const cases = [
    [{ cards: [] }, /unsupported c1 version/],
    [{ c1: 99, b: {}, t: [] }, /unsupported c1 version/],
    [{ c1: 1, t: [] }, /missing body/],
    [{ c1: 1, b: {}, t: {} }, /t is not an array/],
    [{ c1: 1, b: { $c1: 4 }, t: [] }, /out of range/],
    [{ c1: 1, b: { $c1: 0 }, t: [{ n: 2, k: ['a'], c: [{ c: 1, v: ['x'] }] }] }, /does not match/],
    [
      { c1: 1, b: { $c1: 0 }, t: [{ n: 2, k: ['a', 'b'], c: [{ c: 4, r: 1 }, { c: 1, v: ['x', 'y'] }] }] },
      /points forward/,
    ],
    [
      { c1: 1, b: { $c1: 0 }, t: [{ n: 1, k: ['a'], c: [{ c: 2, t: 'nationalities', p: [9999], x: [0] }] }] },
      /refetch \/api\/dictionary/,
    ],
    [
      { c1: 1, b: { $c1: 0 }, t: [{ n: 1, k: ['a'], c: [{ c: 1, v: ['x'], prei: 999 }] }] },
      /refetch \/api\/dictionary/,
    ],
    [{ c1: 1, b: { $c1: 0 }, t: [{ n: 1, k: ['a'], c: [{ c: 7, v: ['x'] }] }] }, /unknown codec/],
    [{ c1: 1, b: { $c1: 0 }, t: [{ n: 2, c: [{ c: 1, v: ['x'], m: [1, 0] }] }] }, /absent cells/],
    [7, /document is not an object/],
  ];
  for (const [payload, message] of cases) {
    assert.throws(() => decodeC1(payload), (error) => {
      assert.ok(error instanceof C1Error, `${JSON.stringify(payload)}: ${error}`);
      assert.match(error.message, message);
      return true;
    });
  }
});

test('an older bundled dictionary reports what to do about a newer code', () => {
  // Append-only means a stale snapshot decodes every code it knows; a code it
  // does not know must be loud, not silently wrong.
  const stale = { ...C1_DICTIONARY, tables: { ...C1_DICTIONARY.tables, nationalities: ['western'] } };
  const payload = {
    c1: 1,
    dict: '1',
    b: { $c1: 0 },
    t: [{ n: 2, k: ['nationality'], c: [{ c: 2, t: 'nationalities', p: [1, 2], x: [0, 1] }] }],
  };
  assert.deepEqual(decodeC1(payload).map((row) => row.nationality), ['western', 'japanese']);
  assert.throws(() => decodeC1(payload, stale), /dictionary nationalities has no code 2/);
});
