import assert from 'node:assert/strict';
import test from 'node:test';
import RAW_SETS from './data/suggest-sets.js';
import TABLE from './data/expansion-nationality.js';
import { compactQuery } from './compact-query.js';
import { expansionNationality } from './expansion-nationality.js';
import { nationalityModule, nationalityTable } from '../../scripts/export-expansion-nationality.mjs';

test('the nationality table is in sync with suggest-sets.js (rerun scripts/export-expansion-nationality.mjs)', () => {
  assert.deepStrictEqual(TABLE, nationalityTable(RAW_SETS));
  assert.ok(nationalityModule(RAW_SETS).startsWith('// Generated by'));
});

test('expansionNationality answers like the set catalog lookup for every set and odd input', () => {
  const byCompact = new Map(RAW_SETS.map((row) => [compactQuery(String(row.display || '').trim()), String(row.nationality || '').trim().toLowerCase()]));
  const oracle = (name) => {
    const compact = compactQuery(name);
    return compact ? byCompact.get(compact) || '' : '';
  };
  const inputs = ['', null, undefined, 0, 'zzz unknown set', 'BASE SET', 'Base Set 2'];
  for (const row of RAW_SETS) inputs.push(row.display, row.slug, row.display.toUpperCase(), ` ${row.display} `);
  for (const input of inputs) assert.equal(expansionNationality(input), oracle(input), String(input));
});
